"""add reset_token to verify_otp

Revision ID: 30069a77e954
Revises: ff5a2ad78650
Create Date: 2026-08-12 11:41:34.189401

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "30069a77e954"
down_revision: Union[str, Sequence[str], None] = "ff5a2ad78650"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("verify_otp", sa.Column("reset_token", sa.String(255), nullable=True))
    op.add_column(
        "verify_otp", sa.Column("reset_token_expires_at", sa.DateTime(), nullable=True)
    )
    op.create_index(
        op.f("ix_verify_otp_reset_token"), "verify_otp", ["reset_token"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_verify_otp_reset_token"), table_name="verify_otp")
    op.drop_column("verify_otp", "reset_token_expires_at")
    op.drop_column("verify_otp", "reset_token")
    # ### end Alembic commands ###
