"""add is_verified to user

Revision ID: 432b2bdeb217
Revises: 
Create Date: 2026-08-11 18:19:59.047075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '432b2bdeb217'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.alter_column('user', 'alamat',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('user', 'latitude',
               existing_type=mysql.DECIMAL(precision=9, scale=6),
               nullable=False)
    op.alter_column('user', 'longitude',
               existing_type=mysql.DECIMAL(precision=9, scale=6),
               nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('verify_otp', 'tujuan',
               existing_type=mysql.ENUM('registrasi', 'reset_password'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verify_otp', 'tujuan',
               existing_type=mysql.ENUM('registrasi', 'reset_password'),
               nullable=True)
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('user', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('user', 'longitude',
               existing_type=mysql.DECIMAL(precision=9, scale=6),
               nullable=True)
    op.alter_column('user', 'latitude',
               existing_type=mysql.DECIMAL(precision=9, scale=6),
               nullable=True)
    op.alter_column('user', 'alamat',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###
