"""recreate verify_otp table with email fk

Revision ID: ff5a2ad78650
Revises: 432b2bdeb217
Create Date: 2026-08-11 18:32:14.904435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5a2ad78650'
down_revision: Union[str, Sequence[str], None] = '432b2bdeb217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
